services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  back:
    image: nexusolo/nest:latest
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
    # Ajoutez un healthcheck pour attendre que PostgreSQL soit prêt
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h postgres -p 5432 -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  front:
    image: nexusolo/vue:latest
    ports:
      - "8081:8080"
    depends_on:
      - back

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5